version: 1.0.{build}
image: Visual Studio 2017
skip_tags: true

branches:
  only:
    - master
    - release

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

before_build:
- pwsh: msbuild -t:Restore

build:
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: minimal

# deploy:
# - provider: NuGet
#   api_key:
#     secure: zZeQU3//rH05N4dUycvkzwQEljtwvDuVk7e+aNBNgZonpUvM0lg0EswTyYtUttv5

for:
-
  branches:
    except:
      - release
  version: $(APPVEYOR_BUILD_VERSION)-pre
