
image: Visual Studio 2017
configuration: Release
skip_tags: true
skip_branch_with_pr: true

branches:
  only:
    - master
    - release

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

before_build:
- pwsh: msbuild -t:Restore

build:
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: minimal

# deploy:
# - provider: NuGet
#   api_key:
#     secure: zZeQU3//rH05N4dUycvkzwQEljtwvDuVk7e+aNBNgZonpUvM0lg0EswTyYtUttv5

for:
-
  version: 1.0.{build}-pre

-
  branches:
    only:
      - release
  version: 1.0.{build}
