version: 1.0.0.{build}
image: Visual Studio 2017
skip_tags: true

init:
- pwsh: appveyor UpdateBuild -Version "${env:APPVEYOR_BUILD_VERSION}-${env:APPVEYOR_REPO_BRANCH}"

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

before_build:
- pwsh: msbuild -t:Restore

build:
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: minimal
